### ISSUE TITLE
mapFromLegacyCameraApi function error

### ISSUE THREAD

**Issue by lcsoka** [dpa99c/cordova-diagnostic-plugin#206]
Hi there,
I got a strange error while using this plugins' isCameraAuthorized function on iOS. It gave the following error:
> Error in Success callbackId: Diagnostic947691512 : TypeError: callback is not a function. (In 'callback(!!result)', 'callback' is an instance of Object)

When i printed out the params variable in Diagnostic.isCameraAuthorized = function(params) i found out that the mapFromLegacyCameraApi function creates an object from it, but it's not working properly. It has a cyclic structure as you can see on the attached image: 
![screen shot 2017-05-12 at 13 38 28](https://cloud.githubusercontent.com/assets/9068178/25996587/559ee4da-3718-11e7-8c94-51544a82ea40.png)

I tend to fix this problem by modifying the function like this
```
function mapFromLegacyCameraApi(args) {
        params = args || {};
        if (typeof arguments[0]  === "function") {
            params = (arguments.length > 2 && typeof arguments[2]  === "object") ? arguments[2] : {};
            params.successCallback = arguments[0];
            if(arguments.length > 1 && typeof arguments[1]  === "function") {
                params.errorCallback = arguments[1];
            }
        }
        return params;
    }
```

Also i'm trying to use this plugin with Ionic 3.2.0 and with ionic-native 3.7.0 and I'm not able to use it with typings, it passes undefined or null as the success callback. (iOS and Android too)

**Comment by dpa99c** [comment]
The cyclic structure created by `mapFromLegacyCameraApi` is fixed by commit 8c81eaaa889e54bfc875956c29e81793ec4eadef and published as `cordova.plugins.diagnostic@3.6.1`.

For the Ionic Typescript wrapper, this contained a bug in the Cordova decorator which I've fixed in commit [45108c4c18a51ad290b03b6bb7e06c46d26c7305](https://github.com/driftyco/ionic-native/commit/45108c4c18a51ad290b03b6bb7e06c46d26c7305) via pull request [#1527](https://github.com/driftyco/ionic-native/pull/1527), however this has not yet made it into an ionic-native release (it's not in `ionic-native@3.7.0).

As a workaround, in your local project, replace `node_modules/@ionic-native/diagnostic/index.js` with  this version: [index.js.zip](https://github.com/dpa99c/cordova-diagnostic-plugin/files/996215/index.js.zip)

**Comment by lcsoka** [comment]
Thank you very much! Although that fix was only for android platform, and i was testing it on iOS. :)

**Comment by dpa99c** [comment]
Oh #$%*, I forgot that iOS and Windows platforms also contain this flawed implementation. Thanks for reminding me. I guess I'll push the fixes to those platforms as v3.6.2.
The pull request that added it has been a pain in the #$%!

**Comment by dpa99c** [comment]
There ya go, iOS and Windows fix published as `cordova.plugins.diagnostic@3.6.2`

**Comment by ThorvaldAagaard** [comment]
I have installed the latest version from you repo, and is getting an error almost as above:
Error in Success callbackId: Diagnostic164729704 : TypeError: params.successCallback is not a function

To me it still looks cyclic but for some reason I am not allowed to post an image
But in the cyclic list both errorCallback and successCallback are defined. 

Could it be an issue with the extrnal storage permission?

I am using it from Ionic2

**Comment by dpa99c** [comment]
@ThorvaldAagaard The cyclic parameters bug should be resolved by v3.6.2. The screenshots below illustrate the presence of the bug in v3.6.0 and the lack of it in v3.6.2 (screenshots from Chrome Dev Tools / Android).

If you are using Ionic 2, you'll also need to apply the manual patch mentioned above to `node_modules/@ionic-native/diagnostic/index.js` until a new version of `ionic-native` is published, since the current version (3.7.0) doesn't contain it.

I'm in the process of creating an Ionic 2 example project, since the majority of reported issues now involve Ionic 2: https://github.com/dpa99c/cordova-diagnostic-plugin-ionic2-example.
It's a work-in-progress, but does contain all the state checking functionality and is what I used to capture the screenshots. 

v3.6.0 (illustrates bug):
![3 6 0](https://cloud.githubusercontent.com/assets/2345062/26025841/3e1c5e5c-37e8-11e7-82e1-514e2051c19b.png)

v3.6.2 (illustrates bug fixed):
![3 6 2](https://cloud.githubusercontent.com/assets/2345062/26025843/49a9f8d8-37e8-11e7-9ffd-de78279e0ca1.png)

**Comment by ThorvaldAagaard** [comment]
I have replaced the index.js, but is still getting the same result.

Is there a way I can check I have the modified index.js in the running app?

Are you blocking upload of images as I am not allow to paste images here, but doing fine in other githubs

**Comment by dpa99c** [comment]
@ThorvaldAagaard

> Is there a way I can check I have the modified index.js in the running app?

index.js is merged into `www/build/main.js` during the Ionic build process, so just run the app on a device, connect Chrome/Safari Dev Tools to remote debug the Webview, then inspect main.js.

Then search for, for example `Diagnostic.prototype, "isCameraAuthorized"`. This should lead you to a block like this:

    __decorate([
        __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["b" /* Cordova */])({ platforms: ['Android', 'iOS'], callbackOrder: 'reverse' }),
        __metadata("design:type", Function),
        __metadata("design:paramtypes", [Boolean]),
        __metadata("design:returntype", Promise)
    ], Diagnostic.prototype, "isCameraAuthorized", null);

`callbackOrder: 'reverse'` indicates this is the manually updated version.

For comparison, [here](http://ge.tt/5LJEL7k2) is an Android debug APK built from the most recent version of [cordova-diagnostic-plugin-ionic2-example](https://github.com/dpa99c/cordova-diagnostic-plugin-ionic2-example) which contains the manual fix and v3.6.2 of the plugin, and runs without the cyclic error. You can debug this at runtime for comparison.

> Are you blocking upload of images as I am not allow to paste images here, but doing fine in other githubs

I don't think it's even possible to block the upload of images, but if it is, I haven't done it. 
I'm able to simply drag+drop images to here, so no idea why it's not working for you.
But if it's not working, just use a 3rd party service like https://pasteboard.co/ and post the link.

**Comment by ThorvaldAagaard** [comment]
Hmm. I can find
 __decorate([
     Cordova({ platforms: ['Android', 'iOS'], callbackOrder: 'reverse' }),
     __metadata("design:type", Function),
     __metadata("design:paramtypes", [Boolean]),
     __metadata("design:returntype", Promise)
 ], Diagnostic.prototype, "isCameraAuthorized", null);

in index.js in node_modules/@ionic-native/diagnostic/index.js

but it is not present in main.js but only the original code
    __decorate([
        __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__plugin__["a" /* Cordova */])({ platforms: ['Android', 'iOS'] })
    ], Diagnostic, "isCameraAuthorized", null);

Is it possible the build process can take the index.js from another location?

**Comment by dpa99c** [comment]
I've just noticed `ionic-native@3.8.1` has been published to npm, which contains the fix anyway. So just do:

    npm uninstall @ionic-native/diagnostic 
      && npm install @ionic-native/diagnostic@latest --save 
      && ionic cordova build android|ios
    
and the bug should be fixed. You can double check by inspecting that `www/build/main.js` then contains:

    __decorate([
        __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["b" /* Cordova */])({ platforms: ['Android', 'iOS'], callbackOrder: 'reverse' }),
        __metadata("design:type", Function),
        __metadata("design:paramtypes", [Boolean]),
        __metadata("design:returntype", Promise)
    ], Diagnostic.prototype, "isCameraAuthorized", null);

**Comment by ThorvaldAagaard** [comment]
This is really strange
I have upgraded to 
"@ionic-native/diagnostic": "^3.8.1"
and can see in package.json that it is ok. 
I can also see the fixed index.js file

but in www/build/main.js it is still the old code

**Comment by ThorvaldAagaard** [comment]
Searching and deleting som modules i found that i have

node_module/ionic-native

in that folder there is a dist-folder, that contains the code

**Comment by ThorvaldAagaard** [comment]
Oh, now I see its not the same version its 2.8.1 and 3.8.1. One for Ionic2 and one for ionic3 - So as im on ionic2 it seems i have to manually fix the 2.8.1 version

**Comment by ThorvaldAagaard** [comment]
Digging a little deeper one of my problems was I imported the old version of Diagnostic, so I needed to import (at)Ionic-Native/diagnostic. But still it seems that the old version will overwrite the newest version. SO now I am trying to get rid of the dependencies for the version 2.8.1 of ionic-native

I'll let you know how it goes

**Comment by ThorvaldAagaard** [comment]
While updating to (at)Ionic-Native I noticed that the Ionic team have released 3.9.2 so I have updated all my native plugins to that version.

I have checked that (at)Ionic-native/diagnostic contains
__decorate([
    Cordova({ platforms: ['Android', 'iOS'], callbackOrder: 'reverse' }),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [Boolean]),
    __metadata("design:returntype", Promise)
], Diagnostic.prototype, "isCameraAuthorized", null);

After the build I have checked that main.js contains
__decorate([
    __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["d" /* Cordova */])({ platforms: ['Android', 'iOS'], callbackOrder: 'reverse' }),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [Boolean]),
    __metadata("design:returntype", Promise)
], Diagnostic.prototype, "isCameraAuthorized", null);

But when executing the result is disappointing
![image](https://cloud.githubusercontent.com/assets/10560652/26173261/7bc8ba96-3b4b-11e7-8cd1-bdacc25bbf7e.png)

But when I look at the code for mapFromLegacyCameraApi

    function mapFromLegacyCameraApi(params) {
        params = params || {};
        if (typeof arguments[0]  === "function") {
            params = (arguments.length > 2 && typeof arguments[2]  === "object") ? arguments[2] : {};
            params.successCallback = arguments[0];
            if(arguments.length > 1 && typeof arguments[1]  === "function") {
                params.errorCallback = arguments[1];
            }
            if(arguments.length > 2 && typeof arguments[2]  === "boolean") {
                params.externalStorage = arguments[1];
            }
        }
        return params;
    }
it looks strange that testing on index 2 but assign the content from index 1 to external storage

and the actual parameters are
![image](https://cloud.githubusercontent.com/assets/10560652/26173555/87d7a83c-3b4c-11e7-81d0-736bc4248abb.png)

so its the input that have the recursive SuccessFunction

Looking at input to callCordovaPlugin it looks like this
![image](https://cloud.githubusercontent.com/assets/10560652/26173821/8586e5f6-3b4d-11e7-99ae-ea461c18a9fb.png)

So it seems the expected change with reverse is in effect.
Any ideas ?

**Comment by dpa99c** [comment]
@ThorvaldAagaard The `mapFromLegacyCameraApi()` you have posted indicates you are using an older version of the plugin which does not contain the bugfix.

This is the [current (fixed) implementation from v3.6.2](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L251):

    function mapFromLegacyCameraApi() {
        var params;
        if (typeof arguments[0]  === "function") {
            params = (arguments.length > 2 && typeof arguments[2]  === "object") ? arguments[2] : {};
            params.successCallback = arguments[0];
            if(arguments.length > 1 && typeof arguments[1]  === "function") {
                params.errorCallback = arguments[1];
            }
        }else { // if (typeof arguments[0]  === "object")
            params = arguments[0];
        }
        return params;
    }
    
This is the [buggy implementation from v3.6.0](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/3.6.0/www/android/diagnostic.js#L251):

    function mapFromLegacyCameraApi(params) {
        params = params || {};
        if (typeof arguments[0]  === "function") {
            params = (arguments.length > 2 && typeof arguments[2]  === "object") ? arguments[2] : {};
            params.successCallback = arguments[0];
            if(arguments.length > 1 && typeof arguments[1]  === "function") {
                params.errorCallback = arguments[1];
            }
            if(arguments.length > 2 && typeof arguments[2]  === "boolean") {
                params.externalStorage = arguments[1];
            }
        }
        return params;
    }

**Comment by ThorvaldAagaard** [comment]
Thx a lot.
I think the issue was that the plugin was installed using npm and that did take precedence to the plugin directory.

Now I am getting the correct version of the plugin and can start my testing
